// The Brain Game's question bank — geography trivia, imported from the
// student's own question set. `category` only steers which pool a
// multiple-choice question borrows its wrong answers from (see
// brain-game-view.tsx) — it isn't shown to the player.

export interface TriviaQuestion {
  id: string;
  question: string;
  answer: string;
  category: "number" | "boolean" | "other";
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { id: "q1", question: "What is the only continent with land in all four hemispheres?", answer: "Africa", category: "other" },
  { id: "q2", question: "Which river flows through the Grand Canyon?", answer: "Colorado River", category: "other" },
  { id: "q3", question: "Where is Angel Falls, the world's largest waterfall, located?", answer: "Venezuela", category: "other" },
  { id: "q4", question: "What is the state capital of New York?", answer: "Albany", category: "other" },
  { id: "q5", question: "On what continent would you find the world's largest desert?", answer: "Antarctica", category: "other" },
  { id: "q6", question: "What is the capital of Ireland?", answer: "Dublin", category: "other" },
  { id: "q7", question: "What is the smallest US state by area?", answer: "Rhode Island", category: "other" },
  { id: "q8", question: "What is the tallest type of tree?", answer: "Redwood", category: "other" },
  { id: "q9", question: "True or False: Holland is a region in The Netherlands?", answer: "True", category: "boolean" },
  { id: "q10", question: "What are the 5 Great Lakes?", answer: "Superior, Michigan, Huron, Erie, and Ontario", category: "other" },
  { id: "q11", question: "Name the 2 countries located within Italy's borders.", answer: "San Marino and Vatican City", category: "other" },
  { id: "q12", question: "How many time zones does the United States have?", answer: "6", category: "number" },
  { id: "q13", question: "What is the world's largest island?", answer: "Greenland", category: "other" },
  { id: "q14", question: "What is the name of China's largest river?", answer: "Yangtze River", category: "other" },
  { id: "q15", question: "Name the country that borders Lesotho.", answer: "South Africa", category: "other" },
  { id: "q16", question: "Which continent has the largest population in the world?", answer: "Asia", category: "other" },
  { id: "q17", question: "Where would you find Mount Everest, the world's tallest mountain?", answer: "China and Nepal", category: "other" },
  { id: "q18", question: "What is North America's longest river?", answer: "Missouri River", category: "other" },
  { id: "q19", question: "What capital city gets the least hours of sunlight per year?", answer: "Tórshavn, Faroe Islands", category: "other" },
  { id: "q20", question: "What is the hottest recorded temperature on Earth?", answer: "134°F / 56.7°C in Death Valley", category: "other" },
  { id: "q21", question: "How many colored rings does the Olympic flag have?", answer: "5", category: "number" },
  { id: "q22", question: "The Union Jack is the flag of what state?", answer: "The United Kingdom", category: "other" },
  { id: "q23", question: "What two symbols appeared on the flag of the USSR?", answer: "Hammer and Sickle", category: "other" },
  { id: "q24", question: "What is the only flag that does not have four sides?", answer: "Nepal", category: "other" },
  { id: "q25", question: "How many stars are on the Chinese flag?", answer: "5", category: "number" },
  { id: "q26", question: "How many colors are used in the South African flag?", answer: "6", category: "number" },
  { id: "q27", question: "What colors are in the flag of the United Nations?", answer: "Blue and white", category: "other" },
  { id: "q28", question: "Which country features a shipwreck on its national flag?", answer: "Bermuda", category: "other" },
  { id: "q29", question: "Which country has a cedar tree on its flag?", answer: "Lebanon", category: "other" },
  { id: "q30", question: "What color is the maple leaf on the Canadian flag?", answer: "Red", category: "other" },
  { id: "q31", question: "How many European capitals does the Danube flow through?", answer: "4 — Vienna, Budapest, Bratislava, Belgrade", category: "other" },
  { id: "q32", question: "The capital of Bulgaria is _ofi_?", answer: "Sofia", category: "other" },
  { id: "q33", question: "What is the capital of Canada?", answer: "Ottawa", category: "other" },
  { id: "q34", question: "In what capital would you find The Little Mermaid statue?", answer: "Copenhagen", category: "other" },
  { id: "q35", question: "On what continent would you find the city of Baku?", answer: "Asia — Azerbaijan", category: "other" },
  { id: "q36", question: "What is the capital of Mexico?", answer: "Mexico City", category: "other" },
  { id: "q37", question: "In what city would you find the Forbidden City?", answer: "Beijing", category: "other" },
  { id: "q38", question: "The capital of Cuba is _ _ van _?", answer: "Havana", category: "other" },
  { id: "q39", question: "True or False: Only 5% of Swiss people live in the capital Bern.", answer: "True", category: "boolean" },
  { id: "q40", question: "Is Kathmandu the capital of Nepal?", answer: "Yes", category: "boolean" },
  { id: "q41", question: "What is the capital of Australia?", answer: "Canberra", category: "other" },
  { id: "q42", question: "Which city is the capital of Iceland?", answer: "Reykjavik", category: "other" },
  { id: "q43", question: "What is the capital of Kenya?", answer: "Nairobi", category: "other" },
  { id: "q44", question: "Which city serves as the capital of Brazil?", answer: "Brasília", category: "other" },
  { id: "q45", question: "What is the capital of Thailand?", answer: "Bangkok", category: "other" },
  { id: "q46", question: 'Which European capital is known as the "City of Light"?', answer: "Paris", category: "other" },
  { id: "q47", question: "What is the capital of Egypt?", answer: "Cairo", category: "other" },
  { id: "q48", question: "Which city is the capital of South Korea?", answer: "Seoul", category: "other" },
  { id: "q49", question: "What is the capital of Argentina?", answer: "Buenos Aires", category: "other" },
  { id: "q50", question: "Which city is the capital of Portugal?", answer: "Lisbon", category: "other" },
  { id: "q51", question: "Which country is the largest in the world by land area?", answer: "Russia", category: "other" },
  { id: "q52", question: "Which country has the most lakes in the world?", answer: "Canada", category: "other" },
  { id: "q53", question: "In which country would you find the city of Krakow?", answer: "Poland", category: "other" },
  { id: "q54", question: "Which country is known as the Land of the Rising Sun?", answer: "Japan", category: "other" },
  { id: "q55", question: "Which African country was formerly known as Abyssinia?", answer: "Ethiopia", category: "other" },
  { id: "q56", question: "Which country has the most pyramids in the world?", answer: "Sudan", category: "other" },
  { id: "q57", question: "What is the smallest country in the world?", answer: "Vatican City", category: "other" },
  { id: "q58", question: "Which country occupies the horn of Africa?", answer: "Somalia", category: "other" },
  { id: "q59", question: "In which country is the world's tallest building located?", answer: "United Arab Emirates", category: "other" },
  { id: "q60", question: "Which country has the most islands?", answer: "Sweden", category: "other" },
  { id: "q61", question: "Which country is both a continent and a country?", answer: "Australia", category: "other" },
  { id: "q62", question: "Which country has three capital cities?", answer: "South Africa", category: "other" },
  { id: "q63", question: "Which country is the largest producer of coffee?", answer: "Brazil", category: "other" },
  { id: "q64", question: "In which country would you find the ancient city of Petra?", answer: "Jordan", category: "other" },
  { id: "q65", question: "Which country is the most populous in Africa?", answer: "Nigeria", category: "other" },
  { id: "q66", question: "Which country is home to the Great Barrier Reef?", answer: "Australia", category: "other" },
  { id: "q67", question: "Which country has the world's oldest continuously used national flag?", answer: "Denmark", category: "other" },
  { id: "q68", question: "Which country is the world's largest landlocked nation?", answer: "Kazakhstan", category: "other" },
  { id: "q69", question: "In which country is the Matterhorn located?", answer: "Switzerland / Italy", category: "other" },
  { id: "q70", question: "Which country has the most volcanoes?", answer: "Indonesia", category: "other" },
  { id: "q71", question: "Which US state has the longest coastline?", answer: "Alaska", category: "other" },
  { id: "q72", question: "What is the highest point in the United States?", answer: "Denali", category: "other" },
  { id: "q73", question: 'Which state is known as the "Sunshine State"?', answer: "Florida", category: "other" },
  { id: "q74", question: "What is the largest US state by land area?", answer: "Alaska", category: "other" },
  { id: "q75", question: "Which river is the longest in the US?", answer: "Missouri River", category: "other" },
  { id: "q76", question: "In which state is the lowest point in North America located?", answer: "California — Death Valley", category: "other" },
  { id: "q77", question: "Which US state is made up entirely of islands?", answer: "Hawaii", category: "other" },
  { id: "q78", question: "What is the most populous US state?", answer: "California", category: "other" },
  { id: "q79", question: "Which state is home to the Everglades?", answer: "Florida", category: "other" },
  { id: "q80", question: "What is the smallest US state?", answer: "Rhode Island", category: "other" },
  { id: "q81", question: 'Which state is known as the "Grand Canyon State"?', answer: "Arizona", category: "other" },
  { id: "q82", question: "Which two states do not border any other US state?", answer: "Alaska and Hawaii", category: "other" },
  { id: "q83", question: "What is the capital of Texas?", answer: "Austin", category: "other" },
  { id: "q84", question: "Which state has the most national parks?", answer: "California", category: "other" },
  { id: "q85", question: "In which state would you find Mount Rushmore?", answer: "South Dakota", category: "other" },
  { id: "q86", question: "Which US state is the leading producer of apples?", answer: "Washington", category: "other" },
  { id: "q87", question: "What is the largest lake entirely within the US?", answer: "Lake Michigan", category: "other" },
  { id: "q88", question: 'Which state is known as the "Magnolia State"?', answer: "Mississippi", category: "other" },
  { id: "q89", question: "What is the capital of California?", answer: "Sacramento", category: "other" },
  { id: "q90", question: "Which state borders the most other states?", answer: "Tennessee and Missouri — 8 each", category: "other" },
  { id: "q91", question: "On which continent is the Sahara Desert located?", answer: "Africa", category: "other" },
  { id: "q92", question: "In which city would you find the Eiffel Tower?", answer: "Paris", category: "other" },
  { id: "q93", question: 'Which continent is known as the "Frozen Continent"?', answer: "Antarctica", category: "other" },
  { id: "q94", question: "Where is the Taj Mahal located?", answer: "India", category: "other" },
  { id: "q95", question: "Which continent has the most countries?", answer: "Africa", category: "other" },
  { id: "q96", question: "In which country is the Machu Picchu landmark located?", answer: "Peru", category: "other" },
  { id: "q97", question: "Which continent is entirely in the Southern Hemisphere?", answer: "Antarctica and Australia", category: "other" },
  { id: "q98", question: "Where would you find the Great Wall?", answer: "China", category: "other" },
  { id: "q99", question: "Which continent is the smallest by land area?", answer: "Australia", category: "other" },
  { id: "q100", question: "In which city is the Colosseum located?", answer: "Rome", category: "other" },
  { id: "q101", question: "Which continent is home to the Amazon Rainforest?", answer: "South America", category: "other" },
  { id: "q102", question: "Where is the Statue of Liberty located?", answer: "New York City, USA", category: "other" },
  { id: "q103", question: "Which continent is the most densely populated?", answer: "Asia", category: "other" },
  { id: "q104", question: "In which country is the Stonehenge landmark?", answer: "United Kingdom", category: "other" },
  { id: "q105", question: "Which continent is the only one without a desert?", answer: "Europe", category: "other" },
];
