/**
 * Data tables for the rule-based Humanizer. Every transformation here is
 * lexical, structural or punctuation-level — nothing is invented. Ported
 * verbatim from Klarity.
 */

/** [sourcePhrase, [replacement options]] — longest phrases are applied first. */
export const VOCAB: [string, string[]][] = [
  ["delve into", ["look at", "dig into", "get into", "go through"]],
  ["delving into", ["looking at", "digging into"]],
  ["delve", ["dig", "look"]],
  ["utilize", ["use"]], ["utilizes", ["uses"]], ["utilizing", ["using"]], ["utilized", ["used"]],
  ["leverage", ["use"]], ["leveraging", ["using"]], ["leverages", ["uses"]],
  ["facilitate", ["help", "make easier"]], ["facilitates", ["helps"]], ["facilitating", ["helping"]],
  ["commence", ["start"]], ["commenced", ["started"]],
  ["endeavor", ["effort", "attempt"]], ["endeavors", ["efforts"]],
  ["a myriad of", ["many", "a lot of", "plenty of"]], ["myriad of", ["many", "lots of"]], ["myriad", ["many"]],
  ["a plethora of", ["plenty of", "a lot of", "loads of"]], ["plethora of", ["plenty of"]], ["plethora", ["plenty"]],
  ["robust", ["strong", "solid", "sturdy"]],
  ["comprehensive", ["complete", "full", "thorough"]],
  ["holistic", ["overall", "whole"]],
  ["seamless", ["smooth", "clean"]], ["seamlessly", ["smoothly", "cleanly", "without a hitch"]],
  ["meticulous", ["careful", "precise"]], ["meticulously", ["carefully", "closely"]],
  ["pivotal", ["key", "central", "big"]],
  ["crucial", ["key", "important", "big"]],
  ["vital", ["key", "necessary"]],
  ["paramount", ["the top priority", "most important"]],
  ["imperative", ["necessary", "a must"]],
  ["quintessential", ["classic", "textbook"]],
  ["in the realm of", ["in", "within"]], ["the realm of", ["the world of"]], ["realm", ["area", "space"]],
  ["a testament to", ["a sign of", "proof of"]], ["testament to", ["proof of"]],
  ["underscores", ["shows", "points to", "drives home"]], ["underscore", ["show", "stress"]],
  ["underscoring", ["showing", "stressing"]],
  ["showcase", ["show", "display"]], ["showcases", ["shows"]], ["showcasing", ["showing"]], ["showcased", ["showed"]],
  ["foster", ["build", "encourage", "grow"]], ["fosters", ["builds", "encourages"]], ["fostering", ["building", "encouraging"]],
  ["cultivate", ["build", "grow"]], ["cultivating", ["building", "growing"]],
  ["garner", ["get", "pick up"]], ["garnered", ["got", "picked up"]], ["garners", ["gets"]],
  ["bolster", ["boost", "back up"]], ["bolsters", ["boosts"]], ["bolstering", ["boosting"]],
  ["spearhead", ["lead"]], ["spearheaded", ["led"]],
  ["encompass", ["cover", "include"]], ["encompasses", ["covers", "includes"]], ["encompassing", ["covering"]],
  ["optimal", ["best", "ideal"]],
  ["invaluable", ["really useful", "hard to replace"]],
  ["indispensable", ["essential", "hard to do without"]],
  ["profound", ["deep", "serious"]],
  ["transformative", ["game changing", "huge"]],
  ["unprecedented", ["record", "new", "one-of-a-kind"]],
  ["unparalleled", ["unmatched", "the best"]],
  ["versatile", ["flexible", "adaptable"]],
  ["nuanced", ["subtle", "detailed"]],
  ["intricate", ["complex", "tricky", "detailed"]],
  ["intricacies", ["details", "fine points"]],
  ["embark on", ["start", "begin", "take on"]], ["embark upon", ["start"]], ["embarking on", ["starting", "taking on"]],
  ["ever-evolving", ["changing", "shifting"]], ["ever evolving", ["changing"]],
  ["cutting-edge", ["new", "advanced", "modern"]], ["state-of-the-art", ["top", "modern"]],
  ["game-changer", ["big deal", "turning point"]],
  ["paradigm shift", ["big shift", "major change"]], ["paradigm", ["model", "approach"]],
  ["synergy", ["teamwork", "overlap"]],
  ["streamline", ["simplify", "tidy up"]], ["streamlines", ["simplifies"]], ["streamlined", ["simple", "tightened up"]],
  ["streamlining", ["simplifying"]],
  ["harness the power of", ["use"]], ["harness", ["use", "tap"]], ["harnessing", ["using", "tapping"]],
  ["unlock", ["open up", "get at"]], ["unlocking", ["opening up"]], ["unlocks", ["opens up"]],
  ["elevate", ["raise", "lift", "improve"]], ["elevates", ["raises", "lifts"]], ["elevating", ["raising"]],
  ["enhance", ["improve", "boost"]], ["enhances", ["improves", "boosts"]], ["enhancing", ["improving"]],
  ["enhanced", ["improved", "better"]],
  ["empower", ["enable", "give people the tools to"]], ["empowers", ["lets"]], ["empowering", ["enabling"]],
  ["revolutionize", ["change", "overhaul"]], ["revolutionizing", ["changing"]],
  ["navigate", ["handle", "deal with", "work through"]], ["navigating", ["handling", "dealing with", "working through"]],
  ["ensure", ["make sure"]], ["ensures", ["makes sure"]], ["ensuring", ["making sure"]],
  ["individuals", ["people"]], ["individual", ["person"]],
  ["numerous", ["many", "a lot of"]], ["various", ["different", "several"]],
  ["obtain", ["get"]], ["obtains", ["gets"]], ["obtained", ["got"]],
  ["require", ["need"]], ["requires", ["needs"]], ["required", ["needed"]],
  ["demonstrate", ["show"]], ["demonstrates", ["shows"]], ["demonstrated", ["showed"]],
  ["assist", ["help"]], ["assists", ["helps"]],
  ["provide", ["give", "offer"]], ["provides", ["gives", "offers"]], ["providing", ["giving"]],
  ["approximately", ["about", "roughly", "around"]],
  ["prior to", ["before"]], ["subsequent to", ["after"]], ["in order to", ["to"]],
  ["due to the fact that", ["because"]], ["owing to the fact that", ["because"]],
  ["a significant number of", ["many"]], ["a wide range of", ["lots of", "all kinds of"]],
  ["a variety of", ["different", "several kinds of"]], ["an array of", ["a set of", "several"]],
  ["when it comes to", ["with", "for"]],
  ["serves as", ["is", "works as"]], ["serve as", ["are", "work as"]],
  ["aims to", ["tries to", "wants to"]], ["aim to", ["try to", "want to"]],
  ["seeks to", ["tries to"]], ["strive to", ["try to"]],
  ["plays a crucial role in", ["matters a lot for", "is key to"]],
  ["plays a vital role in", ["is key to", "matters for"]],
  ["plays a significant role in", ["matters for"]],
  ["pave the way for", ["set up", "open the door for"]],
  ["shed light on", ["explain", "clear up"]],
  ["at the forefront of", ["leading", "ahead in"]],
  ["in the age of", ["now that we have", "with"]],
  ["the digital age", ["today", "now"]],
  ["profound impact", ["big effect"]], ["significant impact", ["big effect", "real effect"]],
  ["rich tapestry", ["mix", "blend"]], ["tapestry", ["mix"]],
  ["the fact that", ["that"]],
  ["it should be noted that", [""]],
  ["arguably", [""]], ["undoubtedly", ["clearly"]], ["notably", [""]],
  ["remarkable", ["impressive", "notable"]],
  ["compelling", ["convincing", "strong"]],
  ["essential", ["needed", "key"]],
  ["significant", ["big", "major", "real"]],
  ["significantly", ["a lot", "much"]],
  ["subsequently", ["later", "then"]],
  ["utilization", ["use"]], ["implementation", ["rollout", "setup"]],
  ["boasts", ["has"]], ["tailored", ["built", "fitted"]],
  ["adept at", ["good at"]], ["prowess", ["skill"]],
  ["unwavering", ["steady"]], ["steadfast", ["steady"]],
  ["captivating", ["gripping"]], ["vibrant", ["lively"]],
  ["in essence", ["basically", "put simply"]],
  ["that being said", ["still", "even so"]],
  ["first and foremost", ["first off", "above all"]],
  ["last but not least", ["finally", "one more thing"]],

  /* second pass: every remaining term the detector penalises needs an exit */
  ["delving", ["digging", "looking"]],
  ["multifaceted", ["many-sided", "complex"]],
  ["embarked on", ["started", "took on"]], ["embarked upon", ["started"]], ["embarks on", ["starts"]],
  ["embark", ["start"]], ["embarking", ["starting"]],
  ["a testament", ["proof"]], ["testament", ["proof"]],
  ["resonate with", ["connect with", "land with"]], ["resonates with", ["connects with"]],
  ["resonate", ["connect"]], ["resonates", ["connects"]],
  ["a beacon of", ["a symbol of"]], ["beacon", ["symbol"]],
  ["cornerstone", ["foundation", "base"]],
  ["ever-evolving landscape", ["changing picture", "shifting scene"]],
  ["evolving landscape", ["changing picture"]],
  ["the landscape of", ["the state of"]], ["landscape", ["picture", "scene", "field"]],
  ["evolving", ["changing", "shifting"]],
  ["this journey", ["this process", "all of this"]], ["the journey", ["the process"]],
  ["exemplifies", ["shows", "is a good example of"]],
  ["adept", ["skilled"]],
  ["myriads", ["many"]],
  ["the world of", ["the field of", ""]],
  ["plays a crucial role", ["matters a lot", "is central"]],
  ["plays a vital role", ["is central", "matters a lot"]],
  ["plays a key role", ["matters a lot"]],
  ["a crucial role", ["a big part"]], ["a vital role", ["a big part"]],
  ["not only", ["not just"]], ["but also", ["but"]],
  ["serves as a", ["is a", "works as a"]], ["serve as a", ["are a"]],
  ["pave the way", ["set things up", "open the door"]],
  ["dive into", ["get into", "look at"]], ["deep dive", ["close look"]],
  ["at the forefront", ["out in front", "leading"]],
  ["holistic approach", ["whole-picture approach", "broad approach"]],
  ["key takeaway", ["main point"]], ["main takeaway", ["main point"]],
  ["due to the fact", ["because"]],
  ["by understanding", ["once you understand", "if you understand"]],
  ["by leveraging", ["by using"]],
  ["is essential for", ["is needed for", "matters for"]],
  ["are essential for", ["are needed for"]],
  ["is crucial for", ["is key for", "matters for"]],
  ["can be attributed to", ["comes down to", "comes from"]],
  ["it is essential to", ["you need to", "it helps to"]],
  ["a wide array of", ["all kinds of", "lots of"]], ["wide array", ["broad mix"]],
  ["has become increasingly", ["is getting more and more", "has been getting more"]],
  ["have become increasingly", ["are getting more and more"]],
  ["in the modern era", ["today", "now"]], ["in the modern world", ["today", "now"]],
  ["fast-paced world", ["busy world"]],
  ["as we navigate", ["as we work through", "while we deal with"]],
  ["navigate the complexities", ["work through the mess", "handle the complications"]],
  ["fostering a", ["building a", "growing a"]],
  ["in the realm", ["in the area"]],
  ["harnessing the power of", ["using"]],
  ["a game changer", ["a big deal"]],
  ["the ever-changing", ["the shifting"]],
];

export const FILLER: RegExp[] = [
  /\bit is important to note that\s*/gi,
  /\bit's important to note that\s*/gi,
  /\bit is worth noting that\s*/gi,
  /\bit's worth noting that\s*/gi,
  /\bit is essential to (?:note|understand|recognize) that\s*/gi,
  /\bin today's fast-?paced (?:world|society|environment|landscape)\s*,?\s*/gi,
  /\bin today's (?:world|society|digital age)\s*,?\s*/gi,
  /\bin the modern (?:world|era|age)\s*,?\s*/gi,
  /\bas we (?:navigate|move) (?:through |into )?(?:the |this )?[\w\s]{0,22}(?:landscape|world|era)\s*,?\s*/gi,
  /\bin conclusion\s*,?\s*/gi,
  /\bto (?:summarize|conclude)\s*,?\s*/gi,
  /\bin summary\s*,?\s*/gi,
  /\boverall\s*,\s*/gi,
  /\bneedless to say\s*,?\s*/gi,
  /\bat the end of the day\s*,?\s*/gi,
  /\bwhen all is said and done\s*,?\s*/gi,
];

export const CONTRACT: [RegExp, string][] = [
  [/\bis not\b/g, "isn't"], [/\bare not\b/g, "aren't"], [/\bwas not\b/g, "wasn't"], [/\bwere not\b/g, "weren't"],
  [/\bdo not\b/g, "don't"], [/\bdoes not\b/g, "doesn't"], [/\bdid not\b/g, "didn't"],
  [/\bwill not\b/g, "won't"], [/\bwould not\b/g, "wouldn't"], [/\bcould not\b/g, "couldn't"],
  [/\bshould not\b/g, "shouldn't"], [/\bcannot\b/g, "can't"], [/\bcan not\b/g, "can't"],
  [/\bhave not\b/g, "haven't"], [/\bhas not\b/g, "hasn't"], [/\bhad not\b/g, "hadn't"],
  [/\bmust not\b/g, "mustn't"], [/\bwe are\b/g, "we're"], [/\bthey are\b/g, "they're"],
  [/\byou are\b/g, "you're"], [/\bit is\b/g, "it's"], [/\bthat is\b/g, "that's"], [/\bthere is\b/g, "there's"],
  [/\bwhat is\b/g, "what's"], [/\bwho is\b/g, "who's"], [/\bhere is\b/g, "here's"],
  [/\bwe will\b/g, "we'll"], [/\bthey will\b/g, "they'll"], [/\byou will\b/g, "you'll"],
  [/\bwe have\b/g, "we've"], [/\bthey have\b/g, "they've"], [/\byou have\b/g, "you've"],
  [/\bwe would\b/g, "we'd"], [/\bthey would\b/g, "they'd"], [/\byou would\b/g, "you'd"],
  [/\bI am\b/g, "I'm"], [/\bI will\b/g, "I'll"], [/\bI have\b/g, "I've"], [/\bI would\b/g, "I'd"],
  [/\blet us\b/g, "let's"],
];

export const TRANSITIONS: [RegExp, string[]][] = [
  [/\bFurthermore,\s*/g, ["Also, ", "On top of that, ", "And ", ""]],
  [/\bMoreover,\s*/g, ["Also, ", "Plus, ", "What's more, ", ""]],
  [/\bAdditionally,\s*/g, ["Also, ", "On top of that, ", ""]],
  [/\bConsequently,\s*/g, ["So ", "As a result, ", "Because of that, "]],
  [/\bTherefore,\s*/g, ["So ", "That means ", "Because of that, "]],
  [/\bHowever,\s*/g, ["But ", "Still, ", "Then again, "]],
  [/\bNevertheless,\s*/g, ["Still, ", "Even so, "]],
  [/\bNonetheless,\s*/g, ["Still, ", "Even so, "]],
  [/\bThus,\s*/g, ["So ", "That means "]],
  [/\bHence,\s*/g, ["So ", "Which is why "]],
  [/\bSubsequently,\s*/g, ["Then ", "After that, "]],
  [/\bUltimately,\s*/g, ["In the end, ", "Finally, ", ""]],
  [/\bSimilarly,\s*/g, ["The same goes for this: ", "Likewise, "]],
  [/\bConversely,\s*/g, ["On the flip side, ", "The opposite happens too: "]],
  [/\bAccordingly,\s*/g, ["So ", "Which is why "]],
  [/\bIn addition,\s*/g, ["Also, ", "Plus, "]],
  [/\bFor instance,\s*/g, ["For example, ", "Say "]],
  [/\bIn particular,\s*/g, ["Especially ", ""]],
  [/\bIt is clear that\s*/g, ["Clearly ", ""]],
  [/\bfurthermore,\s*/g, ["also, ", "and "]],
  [/\bmoreover,\s*/g, ["also, ", "plus, "]],
  [/\badditionally,\s*/g, ["also, "]],
  [/\btherefore,\s*/g, ["so "]],
  [/\bhowever,\s*/g, ["but ", "though "]],
];

export const CASUAL = [
  "Honestly, ", "That said, ", "Still, ", "To be fair, ", "Look, ", "Of course, ", "Then again, ",
  "For the most part, ", "Mostly, ", "In practice, ", "Realistically, ", "Broadly, ",
];

export const OPENER_VARY = [
  "Beyond that, ", "On top of this, ", "Elsewhere, ", "At the same time, ", "In turn, ",
  "From there, ", "Zooming out, ", "Beyond this, ",
];

export const GENERIC_OPENERS = /^(the|this|these|that|those|it|they)$/i;

export const HAS_OPENER =
  /^(And|But|So|Also|Still|Plus|Then|Finally|Now|Yet|Look|Honestly|Of course|That said|To be fair|Then again|What's more|On top of that|In the end|For the most part|Mostly|In practice|Realistically|Broadly|Meanwhile|By contrast|Among them|Things like|Because of that|As a result|Likewise|Especially|There,|It |Beyond that|Beyond this|On top of this|Elsewhere|At the same time|In turn|From there|Zooming out)\b/;

export const BY_NOT_AGENT =
  /^(the end|the time|the way|far|now|then|this point|this time|this stage|comparison|contrast|default|mistake|accident|chance|definition|design|nature|law\b)/i;

export const AGENT_TRAILER_RISK =
  /\b(for|since|during|until|while|before|after|yesterday|today|tomorrow|recently|earlier|later|last|next|this|that|in|on|at|to|from|with|within|among|between|across|throughout|despite|without|under|over|near|against|beyond|through)\b/i;

export const SING_PRONOUN = /^(it|he|she|i|this|that)$/i;
export const PLURAL_PRONOUN = /^(they|we|you|these|those)$/i;
export const OBJ_TO_SUBJ_PRONOUN: Record<string, string> = {
  them: "they", us: "we", him: "he", her: "she", me: "I", it: "it",
};

export const AUXV =
  /^(is|are|was|were|has|have|had|can|could|will|would|may|might|should|must|does|do|did|continues?|remains?|makes?|takes?|gives?|allows?|helps?|leads?|causes?|creates?|provides?|requires?|includes?|involves?|represents?|serves?|enables?|reflects?|shapes?)$/i;

export const PLURAL_VERB =
  /^(were|are|have|do|remain|continue|include|involve|provide|require|allow|enable|help|lead|cause|create|reflect|shape|make|take|give)$/i;
